### ISSUE TITLE
Minified / uglified JavaScript code cannot be tokenized

### ISSUE THREAD

**Issue by hisplan** [pborenstein/confluence2markdown#1]
I have a Jira markdown text something like:

```
{code:javascript}
...some-long-minified-or-uglified-javascript code...
{code}
```

When I ran c2m against it, I got an error message, _"cannot be tokenized"._

**Comment by pborenstein** [comment]
The tokenizer is pretty stupid about how it builds a token. It assumes a token will never be more that 1024 characters long. Clearly, minified JS is way longer than that.

You can bump the value in the tokenizer: https://github.com/pborenstein/node-tokenizer/blob/master/lib/Tokenizer.js#L105

Or you can make the tokenizer smarter.
